from src import *
from fakeoption import *
from indikator import *

def rencaanpembimbingan(driver):
  plus=driver.find_element(By.ID, 'tambahIdentitas').click()
  plus=driver.find_element(By.ID, 'tambahIdentitas').click()
  plus=driver.find_element(By.ID, 'tambahIdentitas').click()
  driver.find_element(By.ID, 'radioButtonJenisProgramKepribadian-0').click()
  driver.find_element(By.ID, 'radioButtonBentukKegiatanKelompok-0').click() 
  driver.find_element(By.ID, 'uraianKegiatan-0').send_keys('uraianKegiatanrencana pembimbingan')  
  tgl_awl = driver.find_element(By.ID, 'tanggalAwalProgram-0')
  tgl_awl.click()
  tgl_awl.send_keys(TglAwalBimbingan)
  tgl_awl.send_keys(Keys.ENTER)
  tgl_akh = driver.find_element(By.ID, 'tanggalAkhirProgram-0')
  tgl_akh.click()
  tgl_akh.send_keys(TglAkhirBimbignan)
  tgl_akh.send_keys(Keys.ENTER) 
  mitra = driver.find_element(By.ID, 'dropdownMitra')
  mitra.click()
  WebDriverWait(driver, 45).until(EC.element_to_be_clickable((By. ID, 'mitra0')))
  mitra.send_keys(Keys.DOWN)
  mitra.send_keys(Keys.ENTER) 
  driver.find_element(By.ID, 'radioButtonModeAbsensiDuaKali-0').click() 
  driver.find_element(By.ID, 'keterangan-0').send_keys(AlamatRumah)
  ############################
  driver.find_element(By.ID, 'radioButtonJenisProgramKepribadian-1').click()  
  driver.find_element(By.ID, 'radioButtonBentukKegiatanIndividu-1').click() 
  driver.find_element(By.ID, 'uraianKegiatan-1').send_keys('uraianKegiatanrencana pembimbingan2')  
  tgl_awl = driver.find_element(By.ID, 'tanggalAwalProgram1')
  tgl_awl.click()
  tgl_awl.send_keys(TglAwalBimbingan)
  tgl_awl.send_keys(Keys.ENTER)
  tgl_akh = driver.find_element(By.ID, 'tanggalAkhirProgram1')
  tgl_akh.click()
  tgl_akh.send_keys(TglAkhirBimbignan)
  tgl_akh.send_keys(Keys.ENTER) 

  mitra = driver.find_element(By.ID, 'dropdownMitra')
  mitra.click()
  WebDriverWait(driver, 45).until(EC.element_to_be_clickable((By. ID, 'mitra0')))
  mitra.send_keys(Keys.DOWN)
  mitra.send_keys(Keys.ENTER) 

  driver.find_element(By.ID, 'radioButtonModeAbsensiSatuKali-1').click() 
  driver.find_element(By.ID, 'keterangan-1').send_keys(AlamatRumah)
  ############################
  driver.find_element(By.ID, 'radioButtonJenisProgramKepribadian-2').click()  
  driver.find_element(By.ID, 'radioButtonBentukKegiatanIndividu-2').click() 
  driver.find_element(By.ID, 'uraianKegiatan-1').send_keys('uraianKegiatanrencana pembimbingan2')  
  tgl_awl = driver.find_element(By.ID, 'tanggalAwalProgram2')
  tgl_awl.click()
  tgl_awl.send_keys(TglAwalBimbingan)
  tgl_awl.send_keys(Keys.ENTER)
  tgl_akh = driver.find_element(By.ID, 'tanggalAkhirProgram2')
  tgl_akh.click()
  tgl_akh.send_keys(TglAkhirBimbignan)
  tgl_akh.send_keys(Keys.ENTER) 

  mitra = driver.find_element(By.ID, 'dropdownMitra')
  mitra.click()
  WebDriverWait(driver, 45).until(EC.element_to_be_clickable((By. ID, 'mitra0')))
  mitra.send_keys(Keys.DOWN)
  mitra.send_keys(Keys.ENTER) 

  driver.find_element(By.ID, 'radioButtonModeAbsensiSatuKali-1').click() 
  driver.find_element(By.ID, 'keterangan-2').send_keys(AlamatRumah)

  klicki(driver)
  driver.find_element(By.ID, 'nextButton').click()
  klicki(driver)
  driver.find_element(By.ID, 'printButton').click()
  Log.info('menunggu loading cetak laporan perencanaa pembimbingan')
  klicki(driver)
  driver.find_element(By.ID, 'nextButton').click()
  driver.find_element(By.ID, 'pilihFoto').click()
  lamaturu(driver)
  pyautogui.write(environ.get(r'FILEPDF'))
  pyautogui.press('enter')
  driver.find_element(By.ID, 'saveButton').click()

