from pytest_html_reporter import attach
from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.common.by import By
import os, platform, time, pytest
import logging
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
#======================REGISTRASI===========REGISTRASI==============REGISTRASI===============================
def Registrasi_Penerimaan(driver):
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    nav2 = driver.find_element(By.ID, 'PP0')
    ActionChains(driver).move_to_element(nav2).perform()
    driver.find_element(By.LINK_TEXT, 'Penerimaan').click()
def Registrasi_penolakan(driver):
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    nav2 = driver.find_element(By.ID, 'PP0')
    ActionChains(driver).move_to_element(nav2).perform()
    driver.find_element(By.ID, "/registrasi/penolakan").click()
def registrasitahanannarapidana(driver):
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    nav2 = driver.find_element(By.ID, "20")
    ActionChains(driver).move_to_element(nav2).perform()
    driver.find_element(By.ID, "/registrasi/registrasi-tahanan-narapidana").click()
def Registrasi_MHP(driver):
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    nav2 = driver.find_element(By.ID, "20")
    ActionChains(driver).move_to_element(nav2).perform()
    nav3 = driver.find_element(By.ID, "RGTRS01")
    ActionChains(driver).move_to_element(nav3).perform()
    driver.find_element(By.ID, "/registrasi/masa-habis-penahanan").click()
def Registrasi_perpanjangnapi(driver):
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    nav2 = driver.find_element(By.ID, "20")
    ActionChains(driver).move_to_element(nav2).perform()
    nav3 = driver.find_element(By.ID, "RGTRS01")
    ActionChains(driver).move_to_element(nav3).perform()
    driver.find_element(By.ID, "/registrasi/perpanjangan-tahanan").click()
def Registrasitahananlanjut(driver):
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    nav2 = driver.find_element(By.ID, "20")
    ActionChains(driver).move_to_element(nav2).perform()
    nav3 = driver.find_element(By.ID, "RGTRS01")
    ActionChains(driver).move_to_element(nav3).perform()
    driver.find_element(By.ID, "/registrasi/penahanan-lanjutan").click()
def Registrasitahananluar(driver):
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    nav2 = driver.find_element(By.ID, "20")
    ActionChains(driver).move_to_element(nav2).perform()
    nav3 = driver.find_element(By.ID, "RGTRS01")
    ActionChains(driver).move_to_element(nav3).perform()
    driver.find_element(By.ID, "/registrasi/tahanan-luar").click()
def Registrasidashremisi(driver):
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    nav2 = driver.find_element(By.ID, "20")
    ActionChains(driver).move_to_element(nav2).perform()
    nav3 = driver.find_element(By.ID, "RGTRS02")
    ActionChains(driver).move_to_element(nav3).perform()
    nav4 = driver.find_element(By.ID, "RO1")
    ActionChains(driver).move_to_element(nav4).perform()
    driver.find_element(By.ID, "/registrasi/dashboard-remisi").click()
def Registrasibukumasuk(driver):
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    nav2 = driver.find_element(By.ID, "20")
    ActionChains(driver).move_to_element(nav2).perform()
    nav3 = driver.find_element(By.ID, "RGTRS02")
    ActionChains(driver).move_to_element(nav3).perform()
    nav4 = driver.find_element(By.ID, "RO1")
    ActionChains(driver).move_to_element(nav4).perform()
    driver.find_element(By.ID, "/registrasi/daftar-buku-masuk").click()
def Registrasi_daftarusulan(driver):
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    nav2 = driver.find_element(By.ID, "20")
    ActionChains(driver).move_to_element(nav2).perform()
    nav3 = driver.find_element(By.ID, "RGTRS02")
    ActionChains(driver).move_to_element(nav3).perform()
    nav4 = driver.find_element(By.ID, "RO1")
    ActionChains(driver).move_to_element(nav4).perform()
    driver.find_element(By.ID, "/registrasi/daftar-usulan").click()
def Registrasi_laporanusulan(driver):
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    nav2 = driver.find_element(By.ID, "20")
    ActionChains(driver).move_to_element(nav2).perform()
    nav3 = driver.find_element(By.ID, "RGTRS02")
    ActionChains(driver).move_to_element(nav3).perform()
    nav4 = driver.find_element(By.ID, "RO1")
    ActionChains(driver).move_to_element(nav4).perform()
    driver.find_element(By.ID, "/registrasi/laporan-usulan").click()
def Registrasisurat_kepremisi(driver):
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    nav2 = driver.find_element(By.ID, "20")
    ActionChains(driver).move_to_element(nav2).perform()
    nav3 = driver.find_element(By.ID, "RGTRS02")
    ActionChains(driver).move_to_element(nav3).perform()
    nav4 = driver.find_element(By.ID, "RO1")
    ActionChains(driver).move_to_element(nav4).perform()
    nav5 = driver.find_element(By.ID, "RO3").click()
    ActionChains(driver).move_to_element(nav5).perform()
    driver.find_element(By.ID, "/registrasi/surat-keputusan-remisi").click()
def Registrasiotprisasisurkep(driver):
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    nav2 = driver.find_element(By.ID, "20")
    ActionChains(driver).move_to_element(nav2).perform()
    nav3 = driver.find_element(By.ID, "RGTRS02")
    ActionChains(driver).move_to_element(nav3).perform()
    nav4 = driver.find_element(By.ID, "RO1")
    ActionChains(driver).move_to_element(nav4).perform()
    nav5 = driver.find_element(By.ID, "RO3").click()
    ActionChains(driver).move_to_element(nav5).perform()
    driver.find_element(By.ID, "/registrasi/otorisasi-surat-keputusan").click()
def Registrasi_pencabutnaperbaikn(driver):
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    nav2 = driver.find_element(By.ID, "20")
    ActionChains(driver).move_to_element(nav2).perform()
    nav3 = driver.find_element(By.ID, "RGTRS02")
    ActionChains(driver).move_to_element(nav3).perform()
    nav4 = driver.find_element(By.ID, "RO1")
    ActionChains(driver).move_to_element(nav4).perform()
    nav5 = driver.find_element(By.ID, "RO3").click()
    ActionChains(driver).move_to_element(nav5).perform()
    driver.find_element(By.ID, "/registrasi/pencabutan-perbaikan-surat-keputusan").click()
def Registrasisurkepremla(driver):
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    nav2 = driver.find_element(By.ID, "20")
    ActionChains(driver).move_to_element(nav2).perform()
    nav4 = driver.find_element(By.ID, "RO1")
    ActionChains(driver).move_to_element(nav4).perform()
    nav5 = driver.find_element(By.ID, "RO3").click()
    ActionChains(driver).move_to_element(nav5).perform()
    driver.find_element(By.ID, "/registrasi/surat-keputusan-remisi-kepala").click()
def Registrasigrasi(driver):
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    nav2 = driver.find_element(By.ID, "20")
    ActionChains(driver).move_to_element(nav2).perform()
    nav3 = driver.find_element(By.ID, "RGTRS02")
    ActionChains(driver).move_to_element(nav3).perform()
    driver.find_element(By.ID, "/registrasi/grasi").click()
def Registrasiremperpid(driver):
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    nav2 = driver.find_element(By.ID, "20")
    ActionChains(driver).move_to_element(nav2).perform()
    nav3 = driver.find_element(By.ID, "RGTRS02")
    ActionChains(driver).move_to_element(nav3).perform()
    driver.find_element(By.ID, "/registrasi/remisi-perubahan-pidana").click()
def Registrasidenda(driver):
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    nav2 = driver.find_element(By.ID, "20")
    ActionChains(driver).move_to_element(nav2).perform()
    nav3 = driver.find_element(By.ID, "RGTRS02")
    ActionChains(driver).move_to_element(nav3).perform()
    nav4 = driver.find_element(By.ID, "3AA").click()
    ActionChains(driver).move_to_element(nav4).perform()
    driver.find_element(By.ID, "/registrasi/pembayaran-denda").click()
def Registrasipembayaranuangpengganti(driver):
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    nav2 = driver.find_element(By.ID, "20")
    ActionChains(driver).move_to_element(nav2).perform()
    nav3 = driver.find_element(By.ID, "RGTRS02")
    ActionChains(driver).move_to_element(nav3).perform()
    nav4 = driver.find_element(By.ID, "3AA").click()
    ActionChains(driver).move_to_element(nav4).perform()
    driver.find_element(By.ID, "/registrasi/pembayaran-uang-pengganti").click()
def Registrasipembayaranrestitusi(driver):
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    nav2 = driver.find_element(By.ID, "20")
    ActionChains(driver).move_to_element(nav2).perform()
    nav3 = driver.find_element(By.ID, "RGTRS02")
    ActionChains(driver).move_to_element(nav3).perform()
    nav4 = driver.find_element(By.ID, "3AA").click()
    ActionChains(driver).move_to_element(nav4).perform()
    driver.find_element(By.ID, "/registrasi/pembayaran-restitusi").click()
def Registrasimutasigol(driver):
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    nav2 = driver.find_element(By.ID, "20")
    ActionChains(driver).move_to_element(nav2).perform()
    driver.find_element(By.ID, "/registrasi/mutasi-golongan").click()
def Registrasi_MAP(driver):
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    nav2 = driver.find_element(By.ID, "20")
    ActionChains(driver).move_to_element(nav2).perform()
    driver.find_element(By.ID, "/registrasi/masih-ada-perkara").click()
def Registrasimutasiupt(driver):
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    nav2 = driver.find_element(By.ID, "20")
    ActionChains(driver).move_to_element(nav2).perform()
    driver.find_element(By.ID, "/registrasi/mutasi-upt").click()
def Registrasibebas(driver):
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    nav2 = driver.find_element(By.ID, "20")
    ActionChains(driver).move_to_element(nav2).perform()
    driver.find_element(By.ID, "/registrasi/pengeluaran-dan-pembebasan").click()
def Registrasimelarikandiri(driver):
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    nav2 = driver.find_element(By.ID, "20")
    ActionChains(driver).move_to_element(nav2).perform()
    driver.find_element(By.ID, "/registrasi/melarikan-diri").click()
def Registrasimasukkembali(driver):
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    nav2 = driver.find_element(By.ID, "20")
    ActionChains(driver).move_to_element(nav2).perform()
    driver.find_element(By.ID, "/registrasi/masuk-kembali").click()
def Registrasisauratsidang(driver):
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    nav2 = driver.find_element(By.ID, "20")
    ActionChains(driver).move_to_element(nav2).perform()
    driver.find_element(By.ID, "/registrasi/surat-sidang").click()
def Registrasimeninggal(driver):
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    nav2 = driver.find_element(By.ID, "20")
    ActionChains(driver).move_to_element(nav2).perform()
    driver.find_element(By.ID, "/registrasi/meninggal-dunia").click()
def Registrasiklasifikasinarkotik(driver):
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    nav2 = driver.find_element(By.ID, "20")
    ActionChains(driver).move_to_element(nav2).perform()
    driver.find_element(By.ID, "/registrasi/klasifikasi-narkotika").click()
def Registrasi_identitas(driver):
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    WebDriverWait(driver, 60).until(EC.element_to_be_clickable((By.ID, '/registrasi/identitas')))
    driver.find_element(By.LINK_TEXT, "Daftar Identitas").click()
def Registrasi_Barangbawaan():
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    driver.find_element(By.ID, "D00").click()
    driver.find_element(By.ID, "/registrasi/barang-bawaan").click()
def Registrasi_mutasi():
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    driver.find_element(By.ID, "D00").click()
    driver.find_element(By.ID, "/registrasi/mutasi").click()
def Registrasi_barang_bawaan():
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    driver.find_element(By.ID, "D00").click()
    driver.find_element(By.ID, "/registrasi/barang-bawaan-biasa").click()
def Registrasi_():
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    driver.find_element(By.ID, "D00").click()
    driver.find_element(By.ID, "/registrasi/barang-bawaan-presiosa").click()
def Registrasi_():
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    driver.find_element(By.ID, "D00").click()
    driver.find_element(By.ID, "/registrasi/penyerahan").click()
def Registrasi_():
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    driver.find_element(By.ID, "AB0").click()
    driver.find_element(By.ID, "/registrasi/penerimaan-anak-bawaan").click()
def Registrasi_():
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    driver.find_element(By.ID, "AB0").click()
    driver.find_element(By.ID, "/registrasi/daftar-anak-bawaan").click()
def Registrasi_():
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    driver.find_element(By.ID, "AB0").click()
    driver.find_element(By.ID, "/registrasi/pengeluaran-anak-bawaan").click()
def Registrasi_():
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    driver.find_element(By.ID, "INTMA").click()
    driver.find_element(By.ID, "/registrasi/perpanjangan-penahanan-ma").click()
def Registrasi_():
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    driver.find_element(By.ID, "INTMA").click()
    driver.find_element(By.ID, "/registrasi/exchange-p48").click()
def Registrasi_():
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    driver.find_element(By.ID, "INTMA").click()
    driver.find_element(By.ID, "/registrasi/exchange-ba17").click()
def Registrasi_():
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    driver.find_element(By.ID, "INTMA").click()
    driver.find_element(By.ID, "/registrasi/sinkronisasi-nik").click()
def Registrasi_():
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    driver.find_element(By.ID, "RGVDT02").click()
    driver.find_element(By.ID, "/registrasi/monitoring-verifikasi-data").click()
def Registrasi_():
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    driver.find_element(By.ID, "RGVDT02").click()
    driver.find_element(By.ID, "/registrasi/ubah-status-registrasi").click()
def Registrasi_():
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    driver.find_element(By.ID, "RGVDT02").click()
    driver.find_element(By.ID, "/registrasi/ubah-ekspirasi-registrasi").click()
def Registrasi_():
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    driver.find_element(By.ID, "RGVDT02").click()
    driver.find_element(By.ID, "/registrasi/validasi-tanggal-ekspirasi").click()
def Registrasi_():
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    driver.find_element(By.ID, "/registrasi/bantuan-hukum").click()
def Registrasi_():
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    nav2 = driver.find_element(By.ID, "30")
    ActionChains(driver).move_to_element(nav2).perform()
    driver.find_element(By.ID, "/registrasi/pembinaan-lanjutan").click()
def Registrasi_():
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    nav2 = driver.find_element(By.ID, "30")
    ActionChains(driver).move_to_element(nav2).perform()
    nav3 = driver.find_element(By.ID, "LAA")
    ActionChains(driver).move_to_element(nav3).perform()
    driver.find_element(By.ID, "/regsitrasi/laporan-remisi").click()
def Registrasi_():
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    nav2 = driver.find_element(By.ID, "30")
    ActionChains(driver).move_to_element(nav2).perform()
    nav3 = driver.find_element(By.ID, "LAA")
    ActionChains(driver).move_to_element(nav3).perform()
    nav4 = driver.find_element(By.ID, "53R")
    ActionChains(driver).move_to_element(nav4).perform()
    driver.find_element(By.ID, "RekapitulasiRemisi").click()
def Registrasi_():
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    driver.find_element(By.ID, "/registrasi/catatan").click()
def Registrasi_():
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    nav2 = driver.find_element(By.ID, "OV0").click()
    ActionChains(driver).move_to_element(nav2).perform()
    driver.find_element(By.ID, "/registrasi/daftar-overstaying").click()
def Registrasi_():
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    nav2 = driver.find_element(By.ID, "OV0").click()
    ActionChains(driver).move_to_element(nav2).perform()
    driver.find_element(By.ID, "/registrasi/rekapitulasi-overstaying").click()
def Registrasi_():
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    driver.find_element(By.ID, "/registrasi/monitoring-sidik-jari-foto").click()
def Registrasi_():
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    driver.find_element(By.ID, "/registrasi/tahapan_pembinaan").click()
def Registrasi_():
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    driver.find_element(By.ID, "/registrasi/highprofile").click()
def Registrasi_():
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    driver.find_element(By.ID, "/registrasi/eksekusi_pm").click()
def Registrasi_():
    nav1 = driver.find_element(By.ID, '01')
    ActionChains(driver).move_to_element(nav1).perform()
    driver.find_element(By.ID, "/registrasi/nomor-daftar-narapidana").click()
#======================REGISTRASI===========REGISTRASI==============REGISTRASI===============================
